### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getCursorBufferPosition' of undefined

### ISSUE THREAD

**Issue by apobbati** [craig-o/atom-jsdoc#14]
[Enter steps to reproduce below:]

1. Close all tabs. Make sure no windows are open.
2. Open the command window and select 'Jsdoc: Block' command.

**Atom Version**: 0.176.0
**System**: Mac OS X 10.9.5
**Thrown From**: [jsdoc](https://github.com/craig-o/atom-jsdoc) package, v0.7.0

### Stack Trace

Uncaught TypeError: Cannot read property 'getCursorBufferPosition' of undefined

```
At /Users/apobbati/.atom/packages/jsdoc/lib/jsdoc.js:85

TypeError: Cannot read property 'getCursorBufferPosition' of undefined
  at atom-workspace.module.exports.writeBlock (/Users/apobbati/.atom/packages/jsdoc/lib/jsdoc.js:85:43)
  at atom-workspace.handler (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/space-pen-extensions.js:115:32)
  at atom-workspace.jQuery.event.dispatch (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:4681:9)
  at atom-workspace.elemData.handle (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:4359:46)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/command-registry.js:243:29)
  at /opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/command-registry.js:3:61
  at CommandPaletteView.module.exports.CommandPaletteView.confirmed (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/node_modules/command-palette/lib/command-palette-view.js:120:32)
  at CommandPaletteView.module.exports.SelectListView.confirmSelection (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/node_modules/go-to-line/node_modules/atom-space-pen-views/lib/select-list-view.js:336:21)
  at space-pen-div.atom.commands.add.core:confirm (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/node_modules/go-to-line/node_modules/atom-space-pen-views/lib/select-list-view.js:109:19)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/command-registry.js:243:29)
  at /opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:558:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:396:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/window-event-handler.js:170:20)

```

### Commands

```
  6x -0:17.5 core:undo (atom-text-editor.editor)
  6x -0:15.4 core:select-up (atom-text-editor.editor)
     -0:14.4 editor:select-to-first-character-of-line (atom-text-editor.editor)
  2x -0:14.2 core:backspace (atom-text-editor.editor)
     -0:13.6 core:move-down (atom-text-editor.editor)
     -0:12.5 core:backspace (atom-text-editor.editor)
     -0:12.2 core:save (atom-text-editor.editor)
     -0:11.8 core:backspace (atom-text-editor.editor)
     -0:08.4 core:save (atom-text-editor.editor)
     -0:06.6 click (div.title.icon.icon-tools)
     -0:05.7 core:close (div.settings-view.pane-item)
     -0:04.9 click (div.close-icon)
     -0:03.8 command-palette:toggle (ul.list-inline.tab-bar.inset-panel)
     -0:01.2 core:move-down (atom-text-editor.editor.mini)
     -0:00.9 core:confirm (atom-text-editor.editor.mini)
     -0:00.9 jsdoc:block (ul.list-inline.tab-bar.inset-panel)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "vim-mode"
    ]
  }
}
```

### Installed Packages

```coffee
# User
Stylus, v0.4.0
atom-beautify, v0.21.2
color-picker, v1.4.4
dart-tools, v0.8.5
emmet, v2.3.2
go-format, v1.0.7
jsdoc, v0.7.0
language-dart, v0.1.1
language-rust, v0.3.5
language-scala, v1.1.0
linter, v0.10.1
linter-jscs, v1.4.9
linter-jshint, v0.1.0
raml, v0.1.0

# Dev
No dev packages
```

/cc @atom/core

**Comment by markotom** [comment]
+1
... same error
